multiple

diff --git a/.github/workflows/deploy_to_prod.yml b/.github/workflows/deploy_to_prod.yml
--- a/.github/workflows/deploy_to_prod.yml
+++ b/.github/workflows/deploy_to_prod.yml
@@ -12,12 +12,14 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      - name: Upgrade urllib3
+        run: pip install --upgrade urllib3
+
       - name: Databricks CLI config
         run: |
-          # Install the Databricks CLI if needed
-          pip install --upgrade urllib3
-          pip install databricks-cli
-         
+          # Install or upgrade the Databricks CLI
+          pip install --upgrade databricks-cli
+
           # Configure the Databricks CLI with your Databricks authentication token
           cat > ~/.databrickscfg << EOF
           [DEFAULT]
@@ -28,8 +30,6 @@ jobs:
 
       - name: Push Changes to Prod Workspace
         run: |
-          # Replace with your Databricks commands to push code and run notebooks in the Prod workspace
-          # Replace with your Databricks command to push the Python script to the Prod workspace
-          databricks workspace import /Repos/meenu.jain@nagarro.com/data-chisel/test_scripts/pytest_script.py /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/pytest_script.py --overwrite --format SOURCE --language PYTHON
-
+          databricks workspace import /Repos/meenu.jain@nagarro.com/data-chisel/test_scripts/pytest_script.py /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/pytest_script.py --overwrite --format SOURCE --language PYTHON || echo "Error importing Python script"
+          
           databricks workspace run-now --notebook /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/pytest_script.py
