Update deploy_to_prod.yml

diff --git a/.github/workflows/deploy_to_prod.yml b/.github/workflows/deploy_to_prod.yml
--- a/.github/workflows/deploy_to_prod.yml
+++ b/.github/workflows/deploy_to_prod.yml
@@ -30,10 +30,5 @@ jobs:
 
       - name: Push Changes to Prod Workspace
         run: |
-          databricks workspace import /Repos/meenu.jain@nagarro.com/data-chisel/test_scripts/pytest_script.py /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/ --language python --overwrite|| echo "Error importing Python script"
+          databricks workspace import /data-chisel/test_scripts/pytest_script.py /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/ --language python --overwrite|| echo "Error importing Python script"
           #databricks workspace run-now --notebook /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/pytest_script.py
-
-      - name: Debugging
-        run: |
-          cat /Repos/meenu.jain@nagarro.com/data-chisel/test_scripts/pytest_script.py"
-          cat /Repos/meenu.jain@nagarro.com/data-chisel/prod_scripts/pytest_script.py"
